services:
  redis:
    image: redis:7
    container_name: grand_nerud_redis

  grand_nerud:
    build:
      context: .
    container_name: grand_nerud_app
    env_file:
      - .env_prod
    command: [ '/grand_nerud/docker/app.sh' ]
    ports:
      - "5005:5003"
    restart: on-failure:10
    volumes:
      - ../uploads:/grand_nerud/uploads/
      - ./app/migrations/versions:/grand_nerud/app/migrations/versions
    depends_on:
      - redis
      - mongo

  celery:
    build:
      context: .
    container_name: grand_nerud_celery
    command: [ '/grand_nerud/docker/celery.sh', 'celery' ]
    env_file:
      - .env_prod
    volumes:
      - ../uploads:/grand_nerud/uploads/
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: grand_nerud_flower
    command: [ '/grand_nerud/docker/celery.sh', 'flower' ]
    env_file:
      - .env_prod
    depends_on:
      - redis
    ports:
      - "5555:5555"

  mongo:
    image: mongo
    container_name: mongodb_grand_nerud
    restart: always
    env_file:
      - .env_prod
    ports:
      - "27017:27017"
    volumes:
      - ../mongo_data_grand_nerud:/data/db